application:
  actions: actions
  web: web-src
  runtimeManifest:
    packages:
      aio-tts-demo-polly:
        license: Apache-2.0
        actions:
          polly:
            function: actions/polly/index.js
            web: 'yes'
            runtime: 'nodejs:14'
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: false
              final: true
